.TH "D:/_WORK/_STEP/InStudyAsp/EFOracle/Model Directory Reference" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/_WORK/_STEP/InStudyAsp/EFOracle/Model Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBExtended\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdbContext\&.cs\fP"
.br
.ti -1c
.RI "file \fBDISCIPLINE\&.cs\fP"
.br
.ti -1c
.RI "file \fBFAQ\&.cs\fP"
.br
.ti -1c
.RI "file \fBGROUP\&.cs\fP"
.br
.ti -1c
.RI "file \fBSCHEDULE\&.cs\fP"
.br
.ti -1c
.RI "file \fBSTUDENT\&.cs\fP"
.br
.ti -1c
.RI "file \fBSTUDENTWORK\&.cs\fP"
.br
.ti -1c
.RI "file \fBTASK\&.cs\fP"
.br
.ti -1c
.RI "file \fBTASKTYPE\&.cs\fP"
.br
.ti -1c
.RI "file \fBTEACHER\&.cs\fP"
.br
.ti -1c
.RI "file \fBUSER\&.cs\fP"
.br
.ti -1c
.RI "file \fBUSER_SESSION\&.cs\fP"
.br
.in -1c
