.TH "D:/_WORK/_STEP/InStudyAsp/Repo Directory Reference" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/_WORK/_STEP/InStudyAsp/Repo Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCommon\fP"
.br
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDisciplineRepository\&.cs\fP"
.br
.ti -1c
.RI "file \fBGroupRepository\&.cs\fP"
.br
.ti -1c
.RI "file \fBScheduleRepository\&.cs\fP"
.br
.ti -1c
.RI "file \fBTeacherRepository\&.cs\fP"
.br
.ti -1c
.RI "file \fBUserRepository\&.cs\fP"
.br
.in -1c
