.TH "D:/_WORK/_STEP/InStudyAsp/InStudyAsp/App_Start Directory Reference" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/_WORK/_STEP/InStudyAsp/InStudyAsp/App_Start Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBNinjectWebCommon\&.cs\fP"
.br
.ti -1c
.RI "file \fBRouteConfig\&.cs\fP"
.br
.in -1c
