.TH "D:/_WORK/_STEP/InStudyAsp/InStudyAsp Directory Reference" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/_WORK/_STEP/InStudyAsp/InStudyAsp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBApp_Start\fP"
.br
.ti -1c
.RI "directory \fBControllers\fP"
.br
.ti -1c
.RI "directory \fBModels\fP"
.br
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGlobal\&.asax\&.cs\fP"
.br
.in -1c
