.TH "EFOracle.Model.USER" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model.USER
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUSER\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUSER_PHONE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUSER_PASSWORD\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUSER_EMAIL\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUSER_FIRSTNAME\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUSER_LASTNAME\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBUSER_BIRTHDAY\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte [] \fBUSER_AVATAR\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBUSER_IS_ACTIVATED\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBSTUDENT\fP > \fBSTUDENTs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBTEACHER\fP > \fBTEACHERs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBUSER_SESSION\fP > \fBUSER_SESSION\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EFOracle\&.Model\&.USER\&.USER ()"

.SH "Property Documentation"
.PP 
.SS "virtual ICollection<\fBSTUDENT\fP> EFOracle\&.Model\&.USER\&.STUDENTs\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBTEACHER\fP> EFOracle\&.Model\&.USER\&.TEACHERs\fC [get]\fP, \fC [set]\fP"

.SS "byte [] EFOracle\&.Model\&.USER\&.USER_AVATAR\fC [get]\fP, \fC [set]\fP"

.SS "DateTime EFOracle\&.Model\&.USER\&.USER_BIRTHDAY\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.USER\&.USER_EMAIL\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.USER\&.USER_FIRSTNAME\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.USER\&.USER_IS_ACTIVATED\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.USER\&.USER_LASTNAME\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.USER\&.USER_PASSWORD\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.USER\&.USER_PHONE\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBUSER_SESSION\fP> EFOracle\&.Model\&.USER\&.USER_SESSION\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
