.TH "EFOracle.Model.SCHEDULE" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model.SCHEDULE \- Specifying view metadata for \fBSCHEDULE\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBInStudyAsp\&.Models\&.User\&.Teacher\&.ViewModelSchedule\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "decimal \fBTEACHER_ID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBGROUP_CODE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBDISCIPLINE_CODE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBSCHEDULE_DATE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBSCHEDULE_ROOM\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBDISCIPLINE\fP \fBDISCIPLINE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBGROUP\fP \fBGROUP\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBTEACHER\fP \fBTEACHER\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specifying view metadata for \fBSCHEDULE\fP class\&. 
.SH "Property Documentation"
.PP 
.SS "virtual \fBDISCIPLINE\fP EFOracle\&.Model\&.SCHEDULE\&.DISCIPLINE\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.SCHEDULE\&.DISCIPLINE_CODE\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBGROUP\fP EFOracle\&.Model\&.SCHEDULE\&.GROUP\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.SCHEDULE\&.GROUP_CODE\fC [get]\fP, \fC [set]\fP"

.SS "DateTime EFOracle\&.Model\&.SCHEDULE\&.SCHEDULE_DATE\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.SCHEDULE\&.SCHEDULE_ROOM\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBTEACHER\fP EFOracle\&.Model\&.SCHEDULE\&.TEACHER\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.SCHEDULE\&.TEACHER_ID\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
