.TH "EFOracle.Model.dbContext" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model.dbContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits DbContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdbContext\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnModelCreating\fP (DbModelBuilder modelBuilder)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual DbSet< \fBDISCIPLINE\fP > \fBDISCIPLINEs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DbSet< \fBFAQ\fP > \fBFAQS\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DbSet< \fBGROUP\fP > \fBGROUPs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DbSet< \fBSCHEDULE\fP > \fBSCHEDULEs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DbSet< \fBSTUDENT\fP > \fBSTUDENTs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DbSet< \fBSTUDENTWORK\fP > \fBSTUDENTWORKs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DbSet< \fBTASK\fP > \fBTASKs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DbSet< \fBTASKTYPE\fP > \fBTASKTYPES\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DbSet< \fBTEACHER\fP > \fBTEACHERs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DbSet< \fBUSER\fP > \fBUSERs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DbSet< \fBUSER_SESSION\fP > \fBUSER_SESSION\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EFOracle\&.Model\&.dbContext\&.dbContext ()"

.SH "Member Function Documentation"
.PP 
.SS "override void EFOracle\&.Model\&.dbContext\&.OnModelCreating (DbModelBuilder modelBuilder)\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "virtual DbSet<\fBDISCIPLINE\fP> EFOracle\&.Model\&.dbContext\&.DISCIPLINEs\fC [get]\fP, \fC [set]\fP"

.SS "virtual DbSet<\fBFAQ\fP> EFOracle\&.Model\&.dbContext\&.FAQS\fC [get]\fP, \fC [set]\fP"

.SS "virtual DbSet<\fBGROUP\fP> EFOracle\&.Model\&.dbContext\&.GROUPs\fC [get]\fP, \fC [set]\fP"

.SS "virtual DbSet<\fBSCHEDULE\fP> EFOracle\&.Model\&.dbContext\&.SCHEDULEs\fC [get]\fP, \fC [set]\fP"

.SS "virtual DbSet<\fBSTUDENT\fP> EFOracle\&.Model\&.dbContext\&.STUDENTs\fC [get]\fP, \fC [set]\fP"

.SS "virtual DbSet<\fBSTUDENTWORK\fP> EFOracle\&.Model\&.dbContext\&.STUDENTWORKs\fC [get]\fP, \fC [set]\fP"

.SS "virtual DbSet<\fBTASK\fP> EFOracle\&.Model\&.dbContext\&.TASKs\fC [get]\fP, \fC [set]\fP"

.SS "virtual DbSet<\fBTASKTYPE\fP> EFOracle\&.Model\&.dbContext\&.TASKTYPES\fC [get]\fP, \fC [set]\fP"

.SS "virtual DbSet<\fBTEACHER\fP> EFOracle\&.Model\&.dbContext\&.TEACHERs\fC [get]\fP, \fC [set]\fP"

.SS "virtual DbSet<\fBUSER_SESSION\fP> EFOracle\&.Model\&.dbContext\&.USER_SESSION\fC [get]\fP, \fC [set]\fP"

.SS "virtual DbSet<\fBUSER\fP> EFOracle\&.Model\&.dbContext\&.USERs\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
