.TH "EFOracle.Model.DISCIPLINE" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model.DISCIPLINE
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDISCIPLINE\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "decimal \fBDISCIPLINE_CODE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDISCIPLINE_NAME\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBSCHEDULE\fP > \fBSCHEDULEs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBTASK\fP > \fBTASKs\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EFOracle\&.Model\&.DISCIPLINE\&.DISCIPLINE ()"

.SH "Property Documentation"
.PP 
.SS "decimal EFOracle\&.Model\&.DISCIPLINE\&.DISCIPLINE_CODE\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.DISCIPLINE\&.DISCIPLINE_NAME\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBSCHEDULE\fP> EFOracle\&.Model\&.DISCIPLINE\&.SCHEDULEs\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBTASK\fP> EFOracle\&.Model\&.DISCIPLINE\&.TASKs\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
