.TH "EFOracle.Model.TEACHER" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model.TEACHER
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTEACHER\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "decimal \fBTEACHER_ID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUSER_PHONE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBTEACHER_START\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBTEACHER_END\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBFAQ\fP > \fBFAQS\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBSCHEDULE\fP > \fBSCHEDULEs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBTASK\fP > \fBTASKs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBUSER\fP \fBUSER\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EFOracle\&.Model\&.TEACHER\&.TEACHER ()"

.SH "Property Documentation"
.PP 
.SS "virtual ICollection<\fBFAQ\fP> EFOracle\&.Model\&.TEACHER\&.FAQS\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBSCHEDULE\fP> EFOracle\&.Model\&.TEACHER\&.SCHEDULEs\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBTASK\fP> EFOracle\&.Model\&.TEACHER\&.TASKs\fC [get]\fP, \fC [set]\fP"

.SS "DateTime EFOracle\&.Model\&.TEACHER\&.TEACHER_END\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.TEACHER\&.TEACHER_ID\fC [get]\fP, \fC [set]\fP"

.SS "DateTime EFOracle\&.Model\&.TEACHER\&.TEACHER_START\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBUSER\fP EFOracle\&.Model\&.TEACHER\&.USER\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.TEACHER\&.USER_PHONE\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
