.TH "EFOracle.Model.TASK" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model.TASK
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTASK\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "decimal \fBTASK_ID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBPARENT_TASK_ID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBDISCIPLINE_CODE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBTASK_DATE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBTASK_TYPE_CODE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTASK_DESCRIPTION\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBTEACHER_ID_FK\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBDISCIPLINE\fP \fBDISCIPLINE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBFAQ\fP > \fBFAQS\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBSTUDENTWORK\fP > \fBSTUDENTWORKs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBTASK\fP > \fBTASK1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBTASK\fP \fBTASK2\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBTASKTYPE\fP \fBTASKTYPE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBTEACHER\fP \fBTEACHER\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EFOracle\&.Model\&.TASK\&.TASK ()"

.SH "Property Documentation"
.PP 
.SS "virtual \fBDISCIPLINE\fP EFOracle\&.Model\&.TASK\&.DISCIPLINE\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.TASK\&.DISCIPLINE_CODE\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBFAQ\fP> EFOracle\&.Model\&.TASK\&.FAQS\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.TASK\&.PARENT_TASK_ID\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBSTUDENTWORK\fP> EFOracle\&.Model\&.TASK\&.STUDENTWORKs\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBTASK\fP> EFOracle\&.Model\&.TASK\&.TASK1\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBTASK\fP EFOracle\&.Model\&.TASK\&.TASK2\fC [get]\fP, \fC [set]\fP"

.SS "DateTime EFOracle\&.Model\&.TASK\&.TASK_DATE\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.TASK\&.TASK_DESCRIPTION\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.TASK\&.TASK_ID\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.TASK\&.TASK_TYPE_CODE\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBTASKTYPE\fP EFOracle\&.Model\&.TASK\&.TASKTYPE\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBTEACHER\fP EFOracle\&.Model\&.TASK\&.TEACHER\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.TASK\&.TEACHER_ID_FK\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
