.TH "EFOracle.Model.GROUP" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model.GROUP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGROUP\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBGROUP_CODE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBSCHEDULE\fP > \fBSCHEDULEs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBSTUDENT\fP > \fBSTUDENTs\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EFOracle\&.Model\&.GROUP\&.GROUP ()"

.SH "Property Documentation"
.PP 
.SS "string EFOracle\&.Model\&.GROUP\&.GROUP_CODE\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBSCHEDULE\fP> EFOracle\&.Model\&.GROUP\&.SCHEDULEs\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBSTUDENT\fP> EFOracle\&.Model\&.GROUP\&.STUDENTs\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
