.TH "EFOracle.Model.TASKTYPE" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model.TASKTYPE
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTASKTYPE\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "decimal \fBTASK_TYPE_CODE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTASK_TYPE_NAME\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBTASK\fP > \fBTASKs\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EFOracle\&.Model\&.TASKTYPE\&.TASKTYPE ()"

.SH "Property Documentation"
.PP 
.SS "decimal EFOracle\&.Model\&.TASKTYPE\&.TASK_TYPE_CODE\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.TASKTYPE\&.TASK_TYPE_NAME\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBTASK\fP> EFOracle\&.Model\&.TASKTYPE\&.TASKs\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
