.TH "EFOracle.Model.FAQ" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model.FAQ
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "decimal \fBSTUDENT_ID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBTASK_ID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBFAQS_QUESTION_TIME\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFAQS_QUESTION\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBTEACHER_ID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBFAQS_ANSWER_TIME\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFAQS_ANSWER\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBSTUDENT\fP \fBSTUDENT\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBTASK\fP \fBTASK\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBTEACHER\fP \fBTEACHER\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string EFOracle\&.Model\&.FAQ\&.FAQS_ANSWER\fC [get]\fP, \fC [set]\fP"

.SS "DateTime EFOracle\&.Model\&.FAQ\&.FAQS_ANSWER_TIME\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.FAQ\&.FAQS_QUESTION\fC [get]\fP, \fC [set]\fP"

.SS "DateTime EFOracle\&.Model\&.FAQ\&.FAQS_QUESTION_TIME\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBSTUDENT\fP EFOracle\&.Model\&.FAQ\&.STUDENT\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.FAQ\&.STUDENT_ID\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBTASK\fP EFOracle\&.Model\&.FAQ\&.TASK\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.FAQ\&.TASK_ID\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBTEACHER\fP EFOracle\&.Model\&.FAQ\&.TEACHER\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.FAQ\&.TEACHER_ID\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
