.TH "EFOracle.Model" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdbContext\fP"
.br
.ti -1c
.RI "class \fBDISCIPLINE\fP"
.br
.ti -1c
.RI "class \fBFAQ\fP"
.br
.ti -1c
.RI "class \fBGROUP\fP"
.br
.ti -1c
.RI "class \fBSCHEDULE\fP"
.br
.RI "Specifying view metadata for \fBSCHEDULE\fP class\&. "
.ti -1c
.RI "class \fBScheduleMetadata\fP"
.br
.ti -1c
.RI "class \fBSTUDENT\fP"
.br
.ti -1c
.RI "class \fBSTUDENTWORK\fP"
.br
.ti -1c
.RI "class \fBTASK\fP"
.br
.ti -1c
.RI "class \fBTASKTYPE\fP"
.br
.ti -1c
.RI "class \fBTEACHER\fP"
.br
.ti -1c
.RI "class \fBUSER\fP"
.br
.ti -1c
.RI "class \fBUSER_SESSION\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
