.TH "EFOracle.Model.STUDENTWORK" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model.STUDENTWORK
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "decimal \fBSTUDENT_ID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBTASK_ID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte [] \fBSTUDENT_WORK_FILE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSTUDENT_WORK_TEXT\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBSTUDENT_WORK_MARK\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBSTUDENT_WORK_DATE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBSTUDENT\fP \fBSTUDENT\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBTASK\fP \fBTASK\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "virtual \fBSTUDENT\fP EFOracle\&.Model\&.STUDENTWORK\&.STUDENT\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.STUDENTWORK\&.STUDENT_ID\fC [get]\fP, \fC [set]\fP"

.SS "DateTime EFOracle\&.Model\&.STUDENTWORK\&.STUDENT_WORK_DATE\fC [get]\fP, \fC [set]\fP"

.SS "byte [] EFOracle\&.Model\&.STUDENTWORK\&.STUDENT_WORK_FILE\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.STUDENTWORK\&.STUDENT_WORK_MARK\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.STUDENTWORK\&.STUDENT_WORK_TEXT\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBTASK\fP EFOracle\&.Model\&.STUDENTWORK\&.TASK\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.STUDENTWORK\&.TASK_ID\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
