.TH "EFOracle.Model.STUDENT" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFOracle.Model.STUDENT
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTUDENT\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "decimal \fBSTUDENT_ID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBGROUP_CODE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBSTUDENT_START\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUSER_PHONE\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBSTUDENT_END\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBFAQ\fP > \fBFAQS\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBGROUP\fP \fBGROUP\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBUSER\fP \fBUSER\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ICollection< \fBSTUDENTWORK\fP > \fBSTUDENTWORKs\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EFOracle\&.Model\&.STUDENT\&.STUDENT ()"

.SH "Property Documentation"
.PP 
.SS "virtual ICollection<\fBFAQ\fP> EFOracle\&.Model\&.STUDENT\&.FAQS\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBGROUP\fP EFOracle\&.Model\&.STUDENT\&.GROUP\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.STUDENT\&.GROUP_CODE\fC [get]\fP, \fC [set]\fP"

.SS "DateTime EFOracle\&.Model\&.STUDENT\&.STUDENT_END\fC [get]\fP, \fC [set]\fP"

.SS "decimal EFOracle\&.Model\&.STUDENT\&.STUDENT_ID\fC [get]\fP, \fC [set]\fP"

.SS "DateTime EFOracle\&.Model\&.STUDENT\&.STUDENT_START\fC [get]\fP, \fC [set]\fP"

.SS "virtual ICollection<\fBSTUDENTWORK\fP> EFOracle\&.Model\&.STUDENT\&.STUDENTWORKs\fC [get]\fP, \fC [set]\fP"

.SS "virtual \fBUSER\fP EFOracle\&.Model\&.STUDENT\&.USER\fC [get]\fP, \fC [set]\fP"

.SS "string EFOracle\&.Model\&.STUDENT\&.USER_PHONE\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
