.TH "InStudyAsp.Models.User.Teacher.TeacherMetadata" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InStudyAsp.Models.User.Teacher.TeacherMetadata \- Methadata for \fBTeacherRegistration\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFirstname\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBLastname\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBEmail\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPhone\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBBirthday\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "HttpPostedFileBase \fBAvatar\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBStart\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPassword\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBConfirmPassword\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Methadata for \fBTeacherRegistration\fP\&. 
.SH "Property Documentation"
.PP 
.SS "HttpPostedFileBase InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherMetadata\&.Avatar\fC [get]\fP, \fC [set]\fP"

.SS "DateTime InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherMetadata\&.Birthday\fC [get]\fP, \fC [set]\fP"

.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherMetadata\&.ConfirmPassword\fC [get]\fP, \fC [set]\fP"

.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherMetadata\&.Email\fC [get]\fP, \fC [set]\fP"

.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherMetadata\&.Firstname\fC [get]\fP, \fC [set]\fP"

.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherMetadata\&.Lastname\fC [get]\fP, \fC [set]\fP"

.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherMetadata\&.Password\fC [get]\fP, \fC [set]\fP"

.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherMetadata\&.Phone\fC [get]\fP, \fC [set]\fP"

.SS "DateTime InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherMetadata\&.Start\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
