.TH "InStudyAsp.Models.User.Teacher.VerificationMailSender" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InStudyAsp.Models.User.Teacher.VerificationMailSender \- Mail sender\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSendVerificationLinkEmail\fP ()"
.br
.RI "Sending mail method\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "MailAddress \fBFromEmail\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "MailAddress \fBToEmail\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFromEmailPassword\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSubject\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBBody\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBLink\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSmtpHost\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBSmtpPort\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Mail sender\&. 
.SH "Member Function Documentation"
.PP 
.SS "void InStudyAsp\&.Models\&.User\&.Teacher\&.VerificationMailSender\&.SendVerificationLinkEmail ()"

.PP
Sending mail method\&. 
.SH "Property Documentation"
.PP 
.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.VerificationMailSender\&.Body\fC [get]\fP, \fC [set]\fP"

.SS "MailAddress InStudyAsp\&.Models\&.User\&.Teacher\&.VerificationMailSender\&.FromEmail\fC [get]\fP, \fC [set]\fP"

.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.VerificationMailSender\&.FromEmailPassword\fC [get]\fP, \fC [set]\fP"

.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.VerificationMailSender\&.Link\fC [get]\fP, \fC [set]\fP"

.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.VerificationMailSender\&.SmtpHost\fC [get]\fP, \fC [set]\fP"

.SS "int InStudyAsp\&.Models\&.User\&.Teacher\&.VerificationMailSender\&.SmtpPort\fC [get]\fP, \fC [set]\fP"

.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.VerificationMailSender\&.Subject\fC [get]\fP, \fC [set]\fP"

.SS "MailAddress InStudyAsp\&.Models\&.User\&.Teacher\&.VerificationMailSender\&.ToEmail\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
