.TH "InStudyAsp.Models.User.Teacher.TeacherLoginValidator" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InStudyAsp.Models.User.Teacher.TeacherLoginValidator \- Login validator\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractValidator< TeacherLogin >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTeacherLoginValidator\fP ()"
.br
.RI "Login validatation rules\&. "
.in -1c
.SH "Detailed Description"
.PP 
Login validator\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherLoginValidator\&.TeacherLoginValidator ()"

.PP
Login validatation rules\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
