.TH "InStudyAsp.Controllers.User.Student" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InStudyAsp.Controllers.User.Student
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestStudentController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
