.TH "InStudyAsp.RouteConfig" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InStudyAsp.RouteConfig
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRegisterRoutes\fP (RouteCollection routes)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void InStudyAsp\&.RouteConfig\&.RegisterRoutes (RouteCollection routes)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
