.TH "InStudyAsp.Models.User.Teacher" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InStudyAsp.Models.User.Teacher
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTeacherLogin\fP"
.br
.RI "ViewModel for Login view\&. "
.ti -1c
.RI "class \fBTeacherLoginValidator\fP"
.br
.RI "Login validator\&. "
.ti -1c
.RI "class \fBTeacherMetadata\fP"
.br
.RI "Methadata for \fBTeacherRegistration\fP\&. "
.ti -1c
.RI "class \fBTeacherRegistration\fP"
.br
.RI "ViewModel for teacherRegistration\&. "
.ti -1c
.RI "class \fBVerificationMailSender\fP"
.br
.RI "Mail sender\&. "
.ti -1c
.RI "class \fBViewModelSchedule\fP"
.br
.RI "ViewModel for ScheduleController\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
