.TH "InStudyAsp.Controllers.User.Student.TestStudentController" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InStudyAsp.Controllers.User.Student.TestStudentController
.SH SYNOPSIS
.br
.PP
.PP
Inherits Controller\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ActionResult \fBIndex\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "ActionResult InStudyAsp\&.Controllers\&.User\&.Student\&.TestStudentController\&.Index ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
