.TH "InStudyAsp.Models.User.Teacher.TeacherLogin" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InStudyAsp.Models.User.Teacher.TeacherLogin \- ViewModel for Login view\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBPhone\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPassword\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBRememberMe\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ViewModel for Login view\&. 
.SH "Property Documentation"
.PP 
.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherLogin\&.Password\fC [get]\fP, \fC [set]\fP"

.SS "string InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherLogin\&.Phone\fC [get]\fP, \fC [set]\fP"

.SS "bool InStudyAsp\&.Models\&.User\&.Teacher\&.TeacherLogin\&.RememberMe\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
