.TH "InStudyAsp.Controllers" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InStudyAsp.Controllers
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUser\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHomeController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
