.TH "D:/_WORK/_STEP/InStudyAsp/InStudyAsp/App_Start/NinjectWebCommon.cs" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/_WORK/_STEP/InStudyAsp/InStudyAsp/App_Start/NinjectWebCommon.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInStudyAsp\&.App_Start\&.NinjectWebCommon\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBInStudyAsp\&.App_Start\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
