.TH "Repo.ScheduleRepository" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Repo.ScheduleRepository
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRepo\&.Common\&.GenericRepository< SCHEDULE >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScheduleRepository\fP (DbContext context)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Repo\&.ScheduleRepository\&.ScheduleRepository (DbContext context)"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
