.TH "Repo.DisciplineRepository" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Repo.DisciplineRepository
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRepo\&.Common\&.GenericRepository< DISCIPLINE >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisciplineRepository\fP (\fBdbContext\fP context)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Repo\&.DisciplineRepository\&.DisciplineRepository (\fBdbContext\fP context)"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
