.TH "TeacherValidator" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TeacherValidator \- Teacher registration validator\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractValidator< TeacherRegistration >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTeacherValidator\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Teacher registration validator\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TeacherValidator\&.TeacherValidator ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
