.TH "D:/_WORK/_STEP/InStudyAsp/InStudyAsp/Models/User/Teacher/TeacherRegistration.cs" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/_WORK/_STEP/InStudyAsp/InStudyAsp/Models/User/Teacher/TeacherRegistration.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInStudyAsp\&.Models\&.User\&.Teacher\&.TeacherRegistration\fP"
.br
.RI "ViewModel for teacherRegistration\&. "
.ti -1c
.RI "class \fBInStudyAsp\&.Models\&.User\&.Teacher\&.TeacherMetadata\fP"
.br
.RI "Methadata for \fBTeacherRegistration\fP\&. "
.ti -1c
.RI "class \fBTeacherValidator\fP"
.br
.RI "Teacher registration validator\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBInStudyAsp\&.Models\&.User\&.Teacher\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
