.TH "D:/_WORK/_STEP/InStudyAsp/InStudyAsp/Controllers/User/Student/TestStudentController.cs" 3 "Fri Sep 22 2017" "InStudyAsp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/_WORK/_STEP/InStudyAsp/InStudyAsp/Controllers/User/Student/TestStudentController.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInStudyAsp\&.Controllers\&.User\&.Student\&.TestStudentController\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBInStudyAsp\&.Controllers\&.User\&.Student\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InStudyAsp from the source code\&.
